/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<opencv2/opencv.hpp>
#include "opencv2/objdetect/objdetect.hpp"
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#include<stdio.h>
 #include <iostream>

using namespace cv;
using namespace std;

/* Header for class com_example_matiz_opencvproject_OpencvNative */

#ifndef _Included_com_example_matiz_opencvproject_OpencvNative
#define _Included_com_example_matiz_opencvproject_OpencvNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_matiz_opencvproject_OpencvNative
 * Method:    convertGray
 * Signature: (JJ)I
 */

int toGray(Mat img, Mat& gray);
JNIEXPORT jint JNICALL Java_com_example_matiz_opencvproject_OpencvNative_convertGray
  (JNIEnv *, jclass, jlong, jlong);

void detectFace(Mat& frame);
JNIEXPORT void JNICALL Java_com_example_matiz_opencvproject_OpencvNative_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
